apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: "public.ecr.aws/k9l7o7t8/ecr-test:1.0.0"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always